func foo() {
  print("foo ran");
  return 0 / 1;
}

func main() {
  try {
    if (1 / 0 == foo()) {
      print("whoops");
    }
  }
  catch "div0" {
    print("div0 in if-condition");
    raise "div0";
  }
  print("must not print");
}

/*
*OUT*
div0 in if-condition
ErrorType.FAULT_ERROR
*OUT*
*/