func main(): void {
 var a: int;
 a = 5;
 foo();
}

func foo(): void {
  print(a);
}

/*
*OUT*
ErrorType.NAME_ERROR
*OUT*
*/
